### PR TITLE
Upgrade to LTS 20.10 (GHC 9.2.5)

### PR DESCRIPTION
**Pull request by kazk**

### CODE REVIEW

**Comment by andys8** [comment]
I remember looking into Haskell and PureScript in the past. How is it going here? 

As of today GHC 9.2.5 is [LTS on stackage](https://www.stackage.org/lts-20.10).


image

**Comment by kazk** [comment]
Thanks for letting me know. I was checking it for a while, but eventually stopped.

We can use 9.2.5 then.

**Comment by kazk** [comment]
Are you interested in working on https://github.com/codewars/hspec-formatters-codewars/issues/2 ? It'd be nice to have in the new version.

**Comment by andys8** [comment]
Awesome thanks

**Pull request merged**
